[package]
name = "rjc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
pest = "2.5.5"
pest_derive = "2.5.5"
