[package]
name = "rjc_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.7.0"
pest_derive = "2.7.0"
rjc_ast = { version = "0.1.0", path = "../rjc_ast" }
